In [1]:
import pandas as pd
import os

file_path = os.path.expanduser('C:/Users/dell/Downloads/DataEngineeringQ2.json')

patientDetails = pd.read_json(file_path)

In [2]:
patientDetails

,_id,appointmentId,patientDetails,phoneNumber,consultationData
0,T6hf3rb5,40d2-9c9f,"{'_id': 'T6hb630b3', 'firstName': 'Css', 'last...",96686896670,"{'adviceTemplates': [], 'advices': [], 'attach..."
1,T65g3rb5,40dbtc9f,"{'_id': 'T6h33b300', 'firstName': 'Lokesh', 'l...",9496368916,"{'adviceTemplates': [], 'advices': [], 'attach..."
2,T7g6Srb5,g3Wt5c9f,"{'_id': 'TjhB4373', 'phrId': '63b5hvy614d5', '...",7787204833,"{'adviceTemplates': [], 'advices': [], 'attach..."
3,94bg8W8d,fb6-a535,"{'_id': '6df4R5b', 'phrId': '644nig7y', 'first...",9376756879,"{'adviceTemplates': [], 'advices': [], 'attach..."
4,T6h8H56c,67h7KL9,"{'_id': 'lK9hy06a', 'firstName': 'Raghu Viju',...",5267384241,"{'adviceTemplates': [], 'advices': [], 'attach..."
5,T9Jh8c8,Hy7Y91,"{'_id': 'kI9d5c6', 'firstName': 'Dinesh Kumar'...",+919826374025,"{'adviceTemplates': [], 'advices': [], 'attach..."
6,9Is624b9,10dY8a-4a,"{'_id': 'i9R324b7', 'phrId': '67Yt2b97', 'firs...",7587265252,"{'adviceTemplates': [], 'advices': [], 'attach..."
7,T8H9c3c6,e8056Ye8,"{'_id': 'T6h41b5ad3d8002ad9c3c4', 'firstName':...",5586958767,"{'adviceTemplates': [], 'advices': [], 'attach..."
8,T8Ud380,dbc0-c66b,"{'_id': 'T9Iy347e', 'firstName': 'Dinesh', 'la...",9987602525,"{'adviceTemplates': [], 'advices': [], 'attach..."
9,T345fG4,1576a7,"{'_id': 'T4Rb1a2', 'firstName': 'Sanjay', 'las...",9234354366,"{'adviceTemplates': [], 'advices': [], 'attach..."
10,T4F6a175,b6Te4ac,"{'_id': 'Tr4T2173', 'phrId': '6E48U79', 'first...",4863281056,"{'adviceTemplates': [], 'advices': [], 'attach..."
11,TW3r002,bu5Qfb,"{'_id': 'T6Wa50', 'firstName': 'Nirmala', 'las...",8687986800,"{'adviceTemplates': [], 'advices': [], 'attach..."
12,6U6Ra36,86U8Y45,"{'_id': '65sRa36', 'firstName': 'Satish', 'las...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
13,u7Y7Aa5,Ufd7231,"{'_id': 'UG67231', 'phrId': 'T6a7231', 'firstN...",7152684236,"{'labTest': [], 'emrTemplates': [], 'doctorNot..."
14,T3R5dec,E4u5Ea2,"{'_id': 'E4u5Ea2', 'firstName': 'Satyanaaryan'...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
15,T4E7Ge6,T4E3e410,"{'_id': 'T4E7Ge6', 'firstName': 'Nivitha', 'la...",9184723620,"{'adviceTemplates': [], 'advices': [], 'attach..."
16,E5336545,04Re22d,"{'_id': '04Re22d', 'firstName': 'Tejpal', 'las...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
17,T7Ys58b,af9784hf,"{'_id': 'u7dWa589', 'firstName': 'Nandhini', '...",5847346075,"{'adviceTemplates': [], 'advices': [], 'attach..."
18,Y874Us5w,I8eW201,"{'_id': 'TU7e913', 'firstName': 'Dhanamma', 'l...",9064537237,"{'adviceTemplates': [], 'advices': [], 'attach..."
19,Y7s5G42,f7r501cb1,"{'_id': 'H8s2d40', 'firstName': 'Kushal', 'las...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
20,Y7eE5cd8,cf092c8t6c,"{'_id': 'u9cd6', 'phrId': '6463U8s231', 'first...",992727892,"{'adviceTemplates': [], 'advices': [], 'attach..."
21,I9984e8,O02n262e,"{'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...",6888324121,"{'adviceTemplates': [], 'advices': [], 'attach..."
22,Tu78a783,5dfN9s41,"{'_id': 'h02U8a781', 'firstName': 'Preethi', '...",8248594521,"{'adviceTemplates': [], 'advices': [], 'attach..."
23,U9D2w6c,cc86re0f,"{'_id': 'T6h40a5ad3d8002ad9c06a', 'firstName':...",+917938475936,"{'adviceTemplates': [], 'advices': [], 'attach..."
24,T6hY6sEe,bd99dU7,"{'_id': 'Y7sHec', 'firstName': 'Naresh', 'last...",+9124648979746,"{'adviceTemplates': [], 'advices': [], 'attach..."
25,H7sT6c,bcWe50,"{'_id': 'T6h408981ayf32b63bcfa', 'firstName': ...",+916883788633,"{'adviceTemplates': [], 'advices': [], 'attach..."
26,8Utyd5b,7au8se3,"{'_id': 'T6U67af9', 'firstName': 'Govardhan', ...",+916636278363,"{'adviceTemplates': [], 'advices': [], 'attach..."
27,y87Ta5c7,432cT213,"{'_id': 'R53Et5W', 'firstName': 'Rajeshwari', ...",6525356535,"{'adviceTemplates': [], 'advices': [], 'attach..."
28,Ub7S65b7,D3fFr42c,"{'_id': 'dE3r$2b5', 'firstName': 'Santosh', 'l...",,"{'adviceTemplates': [], 'advices': [], 'attach..."
29,yD7s2d7,7uyT6Rs,"{'_id': 'TI93Hd5', 'firstName': 'Tarachand', '...",+919093872282,"{'adviceTemplates': [], 'advices': [], 'attach..."
30,I9Sb4e8,O02n2e,"{'_id': 'Pdh97S6', 'phrId': 'Jus0480', 'firstN...",+916888324121,"{'adviceTemplates': [], 'advices': [], 'attach..."

In [ ]:
df = pd.json_normalize(data, sep='_')

def calculate_age(birth_date_str):
    if pd.isnull(birth_date_str) or birth_date_str == '':
        return None
    birth_date = pd.to_datetime(birth_date_str, errors='coerce')
    if pd.isnull(birth_date):
        return None
    today = datetime.today()
    age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
    return age

df['age'] = df['patientDetails_birthDate'].apply(calculate_age)

def categorize_age(age):
    if pd.isna(age):
        return None
    if 0 <= age <= 12:
        return 'Child'
    elif 13 <= age <= 19:
        return 'Teen'
    elif 20 <= age <= 59:
        return 'Adult'
    elif age >= 60:
        return 'Senior'
    else:
        return None

df['ageGroup'] = df['age'].apply(categorize_age)

age_group_counts = df['ageGroup'].value_counts()

adult_count = age_group_counts.get('Adult', 0)

print(adult_count)

In [23]:
medicines_data = pd.json_normalize(data, record_path=['consultationData', 'medicines'], meta=['_id', 'appointmentId'], sep='_')

total_medicines = len(medicines_data)
active_medicines = medicines_data['isActive'].sum()
inactive_medicines = total_medicines - active_medicines

active_percentage = (active_medicines / total_medicines) * 100
inactive_percentage = (inactive_medicines / total_medicines) * 100

print(f"Active Medicines: {active_percentage:.2f}%")
print(f"Inactive Medicines: {inactive_percentage:.2f}%")

Active Medicines: 69.70%
Inactive Medicines: 30.30%

In [21]:
import json
with open(file_path, 'r') as file:
    data = json.load(file)


df = pd.json_normalize(data, sep='_')

def is_valid_indian_phone_number(phone_number):
    phone_number = str(phone_number).strip()
    
    if phone_number.startswith('+91'):
        phone_number = phone_number[3:]
    elif phone_number.startswith('91'):
        phone_number = phone_number[2:]
    
    return len(phone_number) == 10 and phone_number.isdigit() and phone_number[0] in '6789' and 6000000000 <= int(phone_number) <= 9999999999


df['isValidMobile'] = df['phoneNumber'].apply(is_valid_indian_phone_number)


valid_phone_count = df['isValidMobile'].sum()


print(f"Number of valid phone numbers found: {valid_phone_count}")

print(df[['phoneNumber', 'isValidMobile']])

Number of valid phone numbers found: 18
       phoneNumber  isValidMobile
0      96686896670          False
1       9496368916           True
2       7787204833           True
3       9376756879           True
4       5267384241          False
5    +919826374025           True
6       7587265252           True
7       5586958767          False
8       9987602525           True
9       9234354366           True
10      4863281056          False
11      8687986800           True
12                          False
13      7152684236           True
14                          False
15      9184723620          False
16                          False
17      5847346075          False
18      9064537237           True
19                          False
20       992727892          False
21      6888324121           True
22      8248594521           True
23   +917938475936           True
24  +9124648979746          False
25   +916883788633           True
26   +916636278363           True
27      6525356535           True
28                          False
29   +919093872282           True
30   +916888324121           True

In [9]:
columns_of_interest = ['patientDetails_firstName', 'patientDetails_lastName', 'patientDetails_birthDate']

missing_percentages = {}

for column in columns_of_interest:
    total_values = len(df)
    missing_values = df[column].isnull().sum() + (df[column] == '').sum()
    missing_percentage = (missing_values / total_values) * 100
    missing_percentages[column] = round(missing_percentage, 2)

for column, percentage in missing_percentages.items():
    print(f"Missing percentage for {column}: {percentage}%")

Missing percentage for patientDetails_firstName: 0.0%
Missing percentage for patientDetails_lastName: 70.97%
Missing percentage for patientDetails_birthDate: 32.26%

In [10]:
gender_column = 'patientDetails_gender'

mode_gender = df[gender_column].mode()[0]


df[gender_column] = df[gender_column].replace('', None)
df[gender_column].fillna(mode_gender, inplace=True)

total_values = len(df)
female_count = (df[gender_column] == 'F').sum()
female_percentage = (female_count / total_values) * 100

print(f"Percentage of female gender after imputation: {round(female_percentage, 2)}%")

Percentage of female gender after imputation: 32.26%

In [ ]:
medicines_df = pd.json_normalize(data, record_path=['consultationData', 'medicines'])

medicine_counts = medicines_df['medicineName'].value_counts()

third_most_frequent_medicine = medicine_counts.index[2]  
third_most_frequent_count = medicine_counts.iloc[2] 

print(f"hi '{third_most_frequent_medicine}' with {third_most_frequent_count} prescriptions.")